import Post from "./schemas/post"
// import blockContent from "./schemas/blockContent"
import header from "./schemas/header"
// import pet from "./schemas/pet"
import textcard from "./schemas/textcard"
import sportImage from "./schemas/sportImage"
import headings from "./schemas/heading"
import commentss from "./schemas/comment"
import homeFotterImage from "./schemas/homeFotterImage"
import fotter from "./schemas/fotter"
import blog from "./schemas/blog"
import courseCard from "./schemas/courseCard"
import coursecate from "./schemas/coursecate"
import multibutton from "./schemas/multibutton"
import about from "./schemas/about"
import contact from "./schemas/contact"
import navName from "./schemas/navName"
export const schema = {
  types: [header,headings ,textcard,Post,commentss,homeFotterImage,fotter,courseCard,blog,coursecate,multibutton,about,contact,navName]
}
